# Generated by Django 5.0.2 on 2024-04-15 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_aboutbanner_blogbanner_contactbanner_shopbanner_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='Details_photo/')),
                ('title', models.CharField(max_length=255)),
                ('text', models.TextField()),
                ('description', models.CharField(max_length=255)),
            ],
        ),
    ]
