# Generated by Django 5.0.2 on 2024-04-15 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_details'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=55)),
                ('data', models.DateTimeField(auto_now=True)),
                ('comment', models.CharField(max_length=255)),
            ],
        ),
    ]
